# These are supported funding model platforms
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
Deposit USDT through Ethereum Chain ERC20 with the following wallet address
0x9c35B5DfB9A4dA9065B519FE364f70dcA3E980a0
Deposit USDT through Binance Smart Chain BEP20 through following wallet address
0x9c35B5DfB9A4dA9065B519FE364f70dcA3E980a0
Important things
Always copy paste wallet addreses
1st check you are selecting USDT then confirm your smart chain whether its ERC20 or BEP20
And finally thanks for your donation ❤
